### ISSUE TITLE
Lista de preguntas

### ISSUE THREAD

**Issue by Pakoo-8603** [DiegoRosas12/AgroBot#10]
Agreguen lista de cosas

**Comment by Paola-LoEs** [comment]
**MENÚ**
_Agrobot: entrevista para crear perfil_ 
¿Qué tipo de cultivo tienes?
¿Qué tipo de riego usas?
¿Hace cuánto cultivas?

_Consejero: retribución económica a través de publicidad_
Patrocinadores que den cupones por consejos

_Mapa: Ubicación de sembradíos y el tipo de cultivo que hacen_

**Comment by DiegoAGtz** [comment]
## ¿Qué tipo de fertilizantes utilizas?

1. Químico
2. Bio-fertilizante

## ¿Hay árboles en las cercanías de tu campo?

1. Sí
2. No

## ¿Qué tipo de riego tienes?

1. Por aspersión
2. Por goteo
3. Pozo / Río
4. Lluvias de temporal

## ¿Qué cultivas?

1. Uva
2. Chile verde
3. Avena forragera
4. Alfafa
5. Una mezcla

## ¿Para qué lo produces?

1. Consumo personal / familiar
2. Venta

**Comment by DiegoRosas12** [comment]
#bot
#saludo
Buenos días. Soy el Agrobot y te puedo dar consejos para mejorar tu cosecha. ¿Te gustaría escucharlos?

Hola, soy el Agrobot y te puedo ayudar con tu plantación. ¿Te gustaría comenzar a mejorar tu plantío y tener más ganancias?

Me llamo Agrobot y ayudo a los agricultores a generar más y mejores cosechas. Responde "si" si quieres saber más.

**Comment by Pakoo-8603** [comment]
**#saludo #saludo**
### Inicio de la conversación
**[U]:** _Texto random_
**[B]:** Hola, te doy la bienvenida a _"Nombre"_ \n ¿Te interesa generar mayores ingresos con tu cultivo? entonces llegaste al lugar adecuado, aquí podremos darte consejos para mejorar tus cultivos, solo deberás responder unas preguntas. 

### Inicialización de las preguntas.
**[B]:** ¿Qué cultivas? _Elige una da las siguientes respuestas_
**[B]:** 
1.- Uva
2.- Chile verde
3.- Avena forragera
4.- Lechuga

**Comment by BryanMares** [comment]
Dolores Hidalgo es un municipio en el cuál la agricultura es de vital importancia para el desarrollo del mismo, sin embargo, la brecha que existe entre la población y el uso de la tecnología imposibilita el poder tomar medidas que usen demasiada tecnología, lo cual haría que nuestro proyecto sea rechazado por el principal público al que queremos llegar.
Tomando esto en cuenta desarrollamos "Nombre del proyecto", el cual es un BotChat que te da recomendaciones para poder hacer más autosustentable el campo en el que cosechas, provocando con esto un aumento de ganancias para el agricultor y un mejor aprovechamiento de los recursos naturales sin llegar a ser agresivo con el medio ambiente. 

La forma en la que operara este ChatBot es vía SMS (mensaje de texto) esto debido a que la mayoría de los que cosechan no tienen mucha noción del uso de los llamados "Teléfonos inteligentes", de esta manera iremos ayudando a la población para que vaya ingresando al mundo de la tecnología con una herramienta sencilla y eficaz. 

El agricultor mandara un mensaje de texto a "nombre del proyecto" al 2020, seguido de esto recibirá el mensaje de bienvenida del Bot en el cual se le harán preguntas sencillas para generar su perfil del agricultor. 

Los datos obtenidos se utilizaran para armar una base de datos y con esta información poder llegar a financiar este proyecto.

**Comment by DiegoRosas12** [comment]
#bot
#despedida
Gracias por utilizar el Agrobot.
Gracias, espero te hayan servido mis consejos.
Adios. Que tengas buen día/tarde/noche.

**Comment by BryanMares** [comment]
1.-¿Qué tipo de cultivo tienes?

2.-¿Cuantas
