### ISSUE TITLE
Calidad de suelo (características y variables que afectan)

### ISSUE THREAD

**Issue by Pakoo-8603** [DiegoRosas12/AgroBot#6]
pH
Alófanos
Carbonatos
Salinidad
Matéria Orgánica

**Comment by Pakoo-8603** [comment]
pH:

Cuando el pH del medio de cultivo está entre 5.5 y 6.5 se produce una óptima absorción de nutrientes por la mayor parte de las plantas cultivadas.

Se presentarán problemas relacionados con la solubilidad de algunos nutrientes y micro nutrientes, cuando el pH del entorno radicular del cultivo sea superior a 6.5.

Si el pH es inferior a 5.5 la absorción de fósforo se reducirá, lo que puede conducir a la aparición de síntomas carenciales. 

Como consecuencia de un pH inadecuado, las raíces de los cultivos pueden resultar severamente deterioradas antes de que el cultivo muestre síntomas carenciales.  

La cantidad y la calidad de las cosechas pueden verse afectadas tanto por un pH del medio de cultivo alto (suelos alcalinos) como por un nivel bajo (suelos ácidos).

**Comment by BryanMares** [comment]
http://www.agrobit.com/Documentos/G_2_Microemp%5C431_mi000001uv%5B1%5D.htm
